//
// Created by HP on 01.03.2022.
//

#ifndef COURSE_REPLACEALLDIGITASSPACES_H
#define COURSE_REPLACEALLDIGITASSPACES_H

void replaceAllDigitAsSpaces(){

}

#endif //COURSE_REPLACEALLDIGITASSPACES_H
